// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function sumOfEvenfibs(max) {

  let fibs = [1, 1];
  let total = 0;
  while(fibs[fibs.length - 1] < max) {
    let num = fibs[fibs.length - 1] + fibs[fibs.length - 2]
    fibs.push(num);
    if (num % 2 === 0) { total += num }
  }
  return total;

}

console.log(sumOfEvenfibs(4000000)) // 4613732