// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const sumOfEvenFibs = () => {
  let sum = 0;
  let fibs = [1, 1];

  while (fibs[fibs.length - 1] < 4000000) {
    let sumOfFibs = fibs[fibs.length - 1] + fibs[fibs.length - 2];
    fibs.push(sumOfFibs);
    if (sumOfFibs % 2 === 0) {
      sum += sumOfFibs;
    }
  }
  return sum;
};

console.log(sumOfEvenFibs()); // 4613732
